# Generated by Django 4.1.7 on 2023-04-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
